# services:
#   app:
#     image: laravel:10
#     ports:
#       - 8000:8000
#     volumes:
#       - .:/var/www/html
#     depends_on:
#       - db

#   db:
#     image: mysql:8
#     ports:
#       - 3306:3306
#     environment:
#       MYSQL_DATABASE: news_aggregator
#       MYSQL_USER: root
#       MYSQL_PASSWORD: 


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app # This should be your custom image name
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_aggregator
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
